### ISSUE TITLE
Fail to import sotoddb before sotodlib.core

### ISSUE THREAD

**Issue by satoru99** [simonsobs/sotoddb#11]
When I try to import only sotoddb, I get following error:
>\>\>\> import sotoddb
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/takakura/.local/lib/python3.7/site-packages/sotoddb/__init__.py", line 2, in <module>
>     from .loader import SuperLoader
>   File "/home/takakura/.local/lib/python3.7/site-packages/sotoddb/loader.py", line 1, in <module>
>     from sotodlib import core
>   File "/home/takakura/so/sotodlib/sotodlib/core/__init__.py", line 8, in <module>
>     from .context import Context
>   File "/home/takakura/so/sotodlib/sotodlib/core/context.py", line 5, in <module>
>     from . import metadata
>   File "/home/takakura/so/sotodlib/sotodlib/core/metadata.py", line 8, in <module>
>     from sotoddb import ResultSet, DetDB as DetDb, ObsDB as ObsDb, ObsFileDB as ObsFileDb
> ImportError: cannot import name 'ResultSet' from 'sotoddb' (/home/takakura/.local/lib/python3.7/site-packages/sotoddb/__init__.py)

This error does not occur if I import sotodlib.core before sotoddb.

**Comment by mhasself** [comment]
Thanks for the report.  The plan for sotodlib is to merge it completely into sotodlib, and delete this repo.  So bugs related to the direct use of sotoddb are not a priority!  You should have access to all important sotoddb classes through sotodlib.core.metadata, without needing to import sotoddb.  Ping me if that doesn't make sense!
